Advertisement sale prediction from existing customer
LOGISTIC REGRESSION


# importing file into colab


In [ ]:
from google.colab import files
uploaded = files.upload()

#importing libraries

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

# read csv file

In [ ]:
dataset = pd.read_csv('DigitalAd_dataset.csv')

In [ ]:
dataset

S/N  Age  Salary  Status
0      1   18   82000       0
1      2   29   80000       0
2      3   47   25000       1
3      4   45   26000       1
4      5   46   28000       1
..   ...  ...     ...     ...
395  396   35   65000       0
396  397   26   80000       0
397  398   26   52000       0
398  399   20   86000       0
399  400   32   18000       0

[400 rows x 4 columns]

In [ ]:
print (dataset.tail(5))

In [ ]:
print (dataset.shape)

(400, 4)


#segregate the data

In [ ]:
X = dataset.iloc [:, :-1].values
X

array([[    1,    18, 82000],
       [    2,    29, 80000],
       [    3,    47, 25000],
       ...,
       [  398,    26, 52000],
       [  399,    20, 86000],
       [  400,    32, 18000]])

In [ ]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

#splitting dataset to train and test

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split (X, Y, test_size = 0.25, random_state = 0)

# feature scaling to reduce 'age'

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform (x_train)
x_test = sc.fit_transform (x_test)
print (x_train)

[[ 0.41884717  0.97446763  0.56400811]
 [-1.22639344 -1.52088611 -1.28151705]
 [ 0.96432802  0.30264162  0.03671521]
 [-0.38177794 -0.36918439 -0.81281224]
 [ 0.70918375  0.49459191  1.20847722]
 [ 1.21067421 -0.1772341   0.82765456]
 [-1.06802803 -0.27320924 -0.78351819]
 [ 1.28985691  0.39861676  0.24177356]
 [-0.43456641 -0.27320924  0.00742116]
 [ 0.81476069  0.01471619 -0.60775389]
 [-0.93605686  0.11069133  0.00742116]
 [-0.99764341 -0.46515953  2.29235707]
 [ 0.82355877  0.39861676 -0.02187289]
 [-1.59591272 -0.27320924 -1.28151705]
 [ 1.43062616  1.93421906 -1.39869325]
 [ 0.11971252 -0.27320924  2.23376897]
 [ 0.49802988  0.11069133  1.03271291]
 [-1.34956653 -0.56113467  1.44282962]
 [ 0.31327024  0.97446763  1.85294632]
 [ 1.23706844  0.30264162  0.03671521]
 [-0.97124917 -1.13698554 -1.04716465]
 [ 0.18129906 -0.08125895  0.27106761]
 [ 0.27807792  0.30264162 -0.54916579]
 [ 0.26048177 -0.27320924 -0.60775389]
 [ 1.5362031   0.87849248 -1.39869325]
 [-0.53134527  0.78251734

In [ ]:
print (x_test)

[[-4.88879154e-01 -9.51055132e-01  8.70438438e-01]
 [ 9.82246487e-01  1.03030973e+00 -1.09228575e+00]
 [ 1.24821271e+00  2.16251822e+00 -9.73332766e-01]
 [ 4.30532815e-02  1.03030973e+00  8.70438438e-01]
 [ 4.58625497e-01 -1.96249472e-01  3.05411778e-01]
 [-1.08730314e+00 -4.79301594e-01 -1.44914469e+00]
 [-2.97715935e-01 -7.62353717e-01 -5.86735578e-01]
 [ 5.83297161e-01  1.87946609e+00  2.16197043e-01]
 [-4.14076155e-01 -5.73652302e-01 -1.53835943e+00]
 [ 1.92659279e-01  2.75504066e-01  1.56720552e-01]
 [-1.27846636e+00 -1.80021150e+00 -6.75950314e-01]
 [-4.72256265e-01 -7.62353717e-01 -1.70400145e-01]
 [-6.46796596e-01 -1.04540584e+00 -1.03280926e+00]
 [ 1.30639282e+00  9.35959019e-01 -4.97520843e-01]
 [-1.48625247e+00  1.12466043e+00 -1.15176224e+00]
 [-1.09561459e+00 -3.84950887e-01  1.37598861e+00]
 [ 8.49263379e-01  9.35959019e-01  1.37598861e+00]
 [-4.22387599e-01  2.75504066e-01 -5.86735578e-01]
 [ 1.26167724e-01  3.69854774e-01  3.94626514e-01]
 [ 6.79876144e-02 -1.96249472e-

#train the model

In [14]:
from sklearn.linear_model import LogisticRegression


In [15]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

#prediction for all test data

In [16]:
y_pred = model.predict(x_test)

#checking accuracy of prediction

In [17]:
from sklearn.metrics import accuracy_score
print('Accuracy of the model: {0}%'.format (accuracy_score(y_test, y_pred) * 100))

Accuracy of the model: 83.0%
